export const blogPosts = [
    {
        title: 'My first post!',
        date: new Date(),
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consectetur lorem donec massa sapien. Porttitor leo a diam sollicitudin tempor id eu nisl. Sed vulputate mi sit amet mauris commodo quis. Pellentesque pulvinar pellentesque habitant morbi. Enim tortor at auctor urna nunc id cursus metus. Ante in nibh mauris cursus mattis molestie a iaculis at. Consectetur adipiscing elit duis tristique sollicitudin. Libero justo laoreet sit amet cursus. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. In hendrerit gravida rutrum quisque non tellus orci ac. Platea dictumst quisque sagittis purus sit amet volutpat consequat. A erat nam at lectus urna duis. A scelerisque purus semper eget duis at tellus. Condimentum mattis pellentesque id nibh tortor id aliquet lectus proin. Lectus vestibulum mattis ullamcorper velit sed. Facilisis volutpat est velit egestas dui id. Nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Lobortis mattis aliquam faucibus purus in massa.'
    },
    {
        title: 'My second post!',
        date: new Date(),
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consectetur lorem donec massa sapien. Porttitor leo a diam sollicitudin tempor id eu nisl. Sed vulputate mi sit amet mauris commodo quis. Pellentesque pulvinar pellentesque habitant morbi. Enim tortor at auctor urna nunc id cursus metus. Ante in nibh mauris cursus mattis molestie a iaculis at. Consectetur adipiscing elit duis tristique sollicitudin. Libero justo laoreet sit amet cursus. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. In hendrerit gravida rutrum quisque non tellus orci ac. Platea dictumst quisque sagittis purus sit amet volutpat consequat. A erat nam at lectus urna duis. A scelerisque purus semper eget duis at tellus. Condimentum mattis pellentesque id nibh tortor id aliquet lectus proin. Lectus vestibulum mattis ullamcorper velit sed. Facilisis volutpat est velit egestas dui id. Nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Lobortis mattis aliquam faucibus purus in massa.'
    },
    {
        title: 'My third post!',
        date: new Date(),
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consectetur lorem donec massa sapien. Porttitor leo a diam sollicitudin tempor id eu nisl. Sed vulputate mi sit amet mauris commodo quis. Pellentesque pulvinar pellentesque habitant morbi. Enim tortor at auctor urna nunc id cursus metus. Ante in nibh mauris cursus mattis molestie a iaculis at. Consectetur adipiscing elit duis tristique sollicitudin. Libero justo laoreet sit amet cursus. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. In hendrerit gravida rutrum quisque non tellus orci ac. Platea dictumst quisque sagittis purus sit amet volutpat consequat. A erat nam at lectus urna duis. A scelerisque purus semper eget duis at tellus. Condimentum mattis pellentesque id nibh tortor id aliquet lectus proin. Lectus vestibulum mattis ullamcorper velit sed. Facilisis volutpat est velit egestas dui id. Nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames. Lobortis mattis aliquam faucibus purus in massa.'
    }
]